# Use the file format compatible with Docker Compose 3.8
version: "3"

services:

  database:
    # Use the postgres 11.5 base image for this container.
    image: postgres:11.5

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - postgres-compose-network

  web:
    # The root directory from which we're building.
    build: .
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"

    depends_on:
      - database

    networks: 
      - postgres-compose-network

    environment:
      RAILS_ENV: development
      DATABASE_NAME: codetriage_development
      DATABASE_USER: codetriage_development
      DATABASE_PASSWORD: 
      DATABASE_HOST: database
      REDIS_HOST: redis
    
  redis:
    image: redis:5.0.7

# Declare the volumes that our application uses.
volumes:
  db_data:

networks: 
    postgres-compose-network:
      driver: bridge